import React,{useEffect,useState} from 'react';
import {Play,Square,Download,ExternalLink} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ErrorBar,ReferenceArea} from 'recharts';
import {EffectDistribution} from './ResearchStudies.jsx';
import {API,API_ORIGIN} from './api';

const defaults={trust_speed:'0,0.03,0.1,0.3,0.5',incentive:'0,0.2,0.4,0.7,1',transmission:'0,0.05,0.1,0.2,0.4,0.7,1',opinion_speed:'0,0.1,0.3,0.6,1',degree:'2,4,6,8',magnitude:'-50,-10,-1,0,1,10,50',centrality:'0,0.25,0.5,0.75,1'};
const metrics=['coverage','cooperation','mean_trust','disagreement','inequality','largest_component','resource_mean'];
const fmt=v=>v==null?'n/a':Number(v).toPrecision(4);
const ci=s=>s?.ci95?.map(fmt).join(' to ')||'n/a';
export default function ExplorationLab({request,post,world,openExperiment}){
  const [mode,setMode]=useState('sensitivity'),[parameter,setParameter]=useState('transmission'),[values,setValues]=useState(defaults.transmission),[second,setSecond]=useState(''),[secondValues,setSecondValues]=useState('0,0.3,0.6'),[metric,setMetric]=useState('coverage');
  const [count,setCount]=useState(5),[validationCount,setValidationCount]=useState(30),[scales,setScales]=useState('30,50,100'),[topologies,setTopologies]=useState(['small_world','random','scale_free']),[budget,setBudget]=useState(3000),[seconds,setSeconds]=useState(600),[threshold,setThreshold]=useState(.1);
  const [record,setRecord]=useState(null),[history,setHistory]=useState([]),[selected,setSelected]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[archiveState,setArchiveState]=useState(''),[zoom,setZoom]=useState(null);
  const active=record&&['QUEUED','RUNNING','CANCEL_REQUESTED'].includes(record.task?.state||record.state);
  const adopt=r=>{const c=r.configuration;setRecord(r);localStorage.setItem('butterflylab.scan',r.id);setSelected(0);setZoom(null);setMode(c.mode);setParameter(c.parameter);setValues(c.values.join(','));setMetric(c.metric);setSecond(c.second_parameter||'');setSecondValues(c.second_values.join(','));setCount(c.seeds.length);setValidationCount(c.validation_seeds.length);setScales(c.scales.join(','));setTopologies(c.topologies);setBudget(c.max_simulations);setSeconds(c.max_seconds);setThreshold(c.response_threshold);};
  const refresh=async()=>setHistory((await request('/labs')).labs);
  useEffect(()=>{refresh().catch(e=>setError(e.message));const id=localStorage.getItem('butterflylab.scan');if(id)request('/labs/'+id).then(adopt).catch(e=>setError(e.message));},[]);
  useEffect(()=>{const navigate=()=>{if(location.hash==='#criticality')setMode('criticality');if(location.hash==='#sensitivity')setMode('sensitivity')};window.addEventListener('hashchange',navigate);return()=>window.removeEventListener('hashchange',navigate)},[]);
  useEffect(()=>{if(!active)return;let stopped=false;const timer=setInterval(()=>request('/labs/'+record.id).then(r=>{if(!stopped){setRecord(r);if(!['QUEUED','RUNNING','CANCEL_REQUESTED'].includes(r.state))refresh();}}).catch(e=>setError(e.message)),1000);return()=>{stopped=true;clearInterval(timer)};},[record?.id,active]);
  const perform=async fn=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const run=()=>perform(async()=>{
    const r=await request('/labs',post({experiment_name:`Phase 2C / ${mode} / ${parameter}`,world,mode,parameter,values:values.split(',').map(Number),second_parameter:mode==='sensitivity'&&second?second:null,second_values:secondValues.split(',').map(Number),metric,seeds:Array.from({length:Number(count)},(_,i)=>42+i),validation_seeds:Array.from({length:Number(validationCount)},(_,i)=>10042+i),scales:scales.split(',').map(Number),topologies,max_simulations:Number(budget),max_seconds:Number(seconds),response_threshold:Number(threshold),intervention:parameter==='magnitude'||parameter==='centrality'||second==='magnitude'?{kind:'resource',agent:0,magnitude:-1}:null}));adopt(r);await refresh();
  });
  const archive=()=>perform(async()=>{
    const job=await request(`/labs/${record.id}/archive`,post({}));setArchiveState('QUEUED');
    for(;;){const s=await request('/jobs/'+job.job_id);setArchiveState(`${s.state} ${s.completed}/${s.total}`);if(s.state==='COMPLETED'){window.location.assign(API_ORIGIN+job.download_url);break}if(['FAILED','CANCELLED'].includes(s.state))throw new Error(s.error||s.state);await new Promise(r=>setTimeout(r,500));}
  });
  const result=record?.result,cells=result?.cells||[],m=record?.configuration.metric||metric;
  const curve=cells.filter(c=>(c.y==null||c.y===cells[0]?.y)&&(!zoom||c.x>=zoom.low&&c.x<=zoom.high)).sort((a,b)=>a.x-b.x).map(c=>({x:c.x,A:c.summary[m].baseline_mean,B:c.response.mean,error:c.response.ci95?[c.response.mean-c.response.ci95[0],c.response.ci95[1]-c.response.mean]:[0,0]}));
  const all=[...cells,...(result?.validation||[]).flatMap(v=>v.cells||[v])],cell=all[selected];
  const extent=Math.max(.000001,...cells.map(c=>Math.abs(c.summary[m].mean)));
  const regions=result?.regions_after_refinement||result?.regions||[];
  const resourceMax=Math.max(1,...cells.flatMap(c=>[c.summary[m].baseline_mean,c.response.ci95?.[1]??c.response.mean]));
  return <section id="sensitivity" className="exploration-lab">
    <div className="section-heading"><h2>Sensitivity Lab</h2><span className="seed">{record?.id||'PARAMETER RESPONSE / RULE MODE'}</span></div>
    <div id="criticality" className="lab-tabs" role="tablist" aria-label="Research mode">{[['sensitivity','Sensitivity Lab'],['criticality','Criticality Explorer'],['robustness','Robustness Analysis']].map(([v,label])=><button key={v} role="tab" aria-selected={mode===v} onClick={()=>setMode(v)}>{label}</button>)}</div>
    {error&&<p role="alert" className="error-banner">{error}</p>}
    <div className="toolbar">
      <div className="field"><label htmlFor="lab-parameter">Parameter</label><select id="lab-parameter" value={parameter} onChange={e=>{setParameter(e.target.value);setValues(defaults[e.target.value])}}>{Object.keys(defaults).map(p=><option key={p}>{p}</option>)}</select></div>
      <div className="field"><label htmlFor="lab-values">Scan values</label><input id="lab-values" value={values} onChange={e=>setValues(e.target.value)}/></div>
      <div className="field"><label htmlFor="lab-metric">Response metric</label><select id="lab-metric" value={metric} onChange={e=>setMetric(e.target.value)}>{metrics.map(m=><option key={m}>{m}</option>)}</select></div>
      {mode==='sensitivity'&&<><div className="field"><label htmlFor="lab-second">Grid Y parameter</label><select id="lab-second" value={second} onChange={e=>setSecond(e.target.value)}><option value="">Single parameter</option>{Object.keys(defaults).filter(p=>p!==parameter).map(p=><option key={p}>{p}</option>)}</select></div>{second&&<div className="field"><label htmlFor="lab-second-values">Y values</label><input id="lab-second-values" value={secondValues} onChange={e=>setSecondValues(e.target.value)}/></div>}</>}
      <div className="field"><label htmlFor="lab-count">Discovery seeds</label><input id="lab-count" type="number" min="2" max="100" value={count} onChange={e=>setCount(e.target.value)}/><div className="seed-presets">{[5,30,100].map(n=><button key={n} onClick={()=>setCount(n)} aria-pressed={Number(count)===n}>{n}</button>)}</div></div>
      {mode!=='sensitivity'&&<><div className="field"><label htmlFor="lab-validation">Independent seeds</label><input id="lab-validation" type="number" min="2" max="100" value={validationCount} onChange={e=>setValidationCount(e.target.value)}/></div>{mode==='criticality'&&<><div className="field"><label htmlFor="lab-scales">Agent scales</label><input id="lab-scales" value={scales} onChange={e=>setScales(e.target.value)}/></div><div className="field"><label>Validation networks</label>{['small_world','random','scale_free'].map(t=><label key={t}><input type="checkbox" checked={topologies.includes(t)} onChange={e=>setTopologies(e.target.checked?[...topologies,t]:topologies.filter(x=>x!==t))}/>{t}</label>)}</div></>}</>}
      <div className="field"><label htmlFor="lab-budget">Maximum simulations</label><input id="lab-budget" type="number" min="4" max="10000" value={budget} onChange={e=>setBudget(e.target.value)}/></div>
      <div className="field"><label htmlFor="lab-seconds">Runtime budget / seconds</label><input id="lab-seconds" type="number" min="1" max="3600" value={seconds} onChange={e=>setSeconds(e.target.value)}/></div>
      {mode==='criticality'&&<div className="field"><label htmlFor="lab-threshold">Minimum adjacent response / metric units</label><input id="lab-threshold" type="number" min=".000001" step=".01" value={threshold} onChange={e=>setThreshold(e.target.value)}/></div>}
      <button className="run" disabled={active||busy||!world?.engine} onClick={run}><Play size={14}/>Run scan</button>
    </div>
    <div className="run-status"><span>{record?.task?.state||record?.state||'Ready'} / {record?.task?.completed||0} of {record?.task?.total||0} simulations</span>{active&&<button className="export" onClick={()=>perform(()=>request(`/labs/${record.id}/cancel`,post({})))}><Square size={14}/>Cancel scan</button>}</div>
    {active&&<progress value={record.task?.completed||0} max={record.task?.total||1}/>}
    <div className="field"><label htmlFor="lab-history">Saved scans</label><select id="lab-history" value={record?.id||''} onChange={e=>perform(async()=>adopt(await request('/labs/'+e.target.value)))}><option value="">Select scan</option>{history.map(r=><option key={r.id} value={r.id}>{r.created_at} / {r.state} / {r.id.slice(0,8)}</option>)}</select></div>
    {!!cells.length&&<>
      <div className="section-heading"><h3>{record.configuration.mode==='criticality'?'Criticality Explorer':'Parameter response'} / {m}</h3><div className="actions"><a className="export" href={`${API}/labs/${record.id}/export`} download><Download size={14}/>Summary JSON</a><button className="export" disabled={active||busy} onClick={archive}><Download size={14}/>Full archive</button><span role="status">{archiveState}</span></div></div>
      <div className="plot lab-response"><ResponsiveContainer width="100%" height="100%"><LineChart data={curve} margin={{top:15,right:25,bottom:25,left:15}}><CartesianGrid stroke="#304043" strokeDasharray="3 3"/><XAxis dataKey="x" type="number" domain={['dataMin','dataMax']} stroke="#c0cac4" label={{value:record.configuration.parameter,position:'insideBottom',offset:-15,fill:'#c0cac4'}}/><YAxis domain={m==='resource_mean'?[0,resourceMax]:[0,1]} stroke="#c0cac4" label={{value:m==='resource_mean'?'resource units / Agent':'ratio [0,1]',angle:-90,position:'insideLeft',fill:'#c0cac4'}}/><Tooltip contentStyle={{background:'#151d1f'}}/><Legend verticalAlign="top"/>{regions.filter(r=>r.candidate).map(r=><ReferenceArea key={r.low} x1={r.low} x2={r.high} fill="#d3b96c" fillOpacity={.14}/>)}<Line dataKey="A" name="A / baseline mean" stroke="#a9ddc6" isAnimationActive={false}/><Line dataKey="B" name="B / response mean + 95% interval" stroke="#de8877" isAnimationActive={false}><ErrorBar dataKey="error" width={4} stroke="#de8877"/></Line></LineChart></ResponsiveContainer></div>
      {record.configuration.second_parameter&&<div className="table-scroll"><p>Response curve slice: {record.configuration.second_parameter} = {cells[0]?.y}</p><table className="heatmap"><thead><tr><th>{record.configuration.second_parameter} ↓ / {record.configuration.parameter} →</th>{record.configuration.values.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{record.configuration.second_values.map(y=><tr key={y}><th>{y}</th>{record.configuration.values.map(x=>{const c=cells.find(c=>c.x===x&&c.y===y),v=c?.summary[m].mean;return <td key={x} style={{background:v==null?'transparent':`rgba(${v>=0?'169,221,198':'222,136,119'},${.1+.55*Math.abs(v)/extent})`}}>{fmt(v)}</td>})}</tr>)}</tbody></table><p className="limitations">Mean paired B−A; symmetric color scale ±{fmt(extent)}.</p></div>}
      {regions.length>0&&<><div className="actions"><button className="export" disabled={!zoom} onClick={()=>setZoom(null)}>Full parameter range</button><span>{zoom?`${zoom.low} to ${zoom.high}`:'Full range'}</span></div><div className="table-scroll"><table><thead><tr><th>Candidate interval</th><th>Adjacent change</th><th>95% interval</th><th>Classification</th></tr></thead><tbody>{regions.map(r=><tr key={r.low}><td><button className="text-button" title="Zoom response interval" onClick={()=>setZoom(r)}>{r.low} to {r.high}</button></td><td>{fmt(r.change.mean)}</td><td>{ci(r.change)}</td><td>{r.classification}</td></tr>)}</tbody></table></div></>}
      {result.candidate_detected!=null&&<p className="notice">Candidate region: {result.candidate_detected?'observed':'not detected'} / stable across independent seeds, sizes and networks: {result.stable_in_validation?'yes':'not established'}</p>}
      <div className="table-scroll"><table><thead><tr><th>Parameter / phase</th><th>Seeds</th><th>Normalized cost</th><th>Mean B−A</th><th>Sample SD</th><th>95% interval</th><th>Direction consistency</th><th>Trajectory</th></tr></thead><tbody>{all.map((c,i)=><tr key={c.experiment_id}><td><button className="text-button" onClick={()=>setSelected(i)}>{c.x}{c.y==null?'':` / ${c.y}`} / {c.phase} / N={c.world.population} {c.world.network}</button></td><td>{c.seeds.length}</td><td>{c.cost}</td><td>{fmt(c.summary[m].mean)}</td><td>{fmt(c.summary[m].std)}</td><td>{ci(c.summary[m])}</td><td>{fmt(c.summary[m].direction_consistency)}</td><td><button title="Open experiment" className="icon-button" onClick={()=>openExperiment(c.experiment_id)}><ExternalLink size={15}/></button></td></tr>)}</tbody></table></div>
      {cell&&<><h3>Selected response / {cell.x} / {cell.phase} / {cell.experiment_id}</h3><EffectDistribution result={cell} metric={m}/></>}
      <p className="limitations">{result.note} Intervals are descriptive paired bootstrap intervals, without multiplicity correction. Preset seed counts are runtime choices, not significance standards. Zero effects have no consistent direction. Network density is recorded per seed in the export.</p>
    </>}
  </section>;
}
